uploads = []

[[generated]]
id = "wT7-W_AXSWbRnGigbpB5d"
uri = "file://artifacts/pricedug/assets/images/icon.png"
type = "image"
title = "priced ug app icon"

[[outputs]]
id = "mITrqQ6QBdanvyuNuB6pZ"
uri = "file://exports/expo-qr.png"
type = "image"
title = "Priced Ug — Expo Go QR code"

[[outputs]]
id = "-AjnENn9jRzr992xD4yqv"
uri = "file://artifacts/pricedug/assets/store/play-store-icon-512.png"
type = "image"
title = "Priced Ug — Play Store Icon (512×512, squircle)"
