kind = "mobile"
previewPath = "/"
title = "Pricedug"
version = "1.0.0"
id = "artifacts/pricedug"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 26152

[services.development]
run = "pnpm --filter @workspace/pricedug run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/pricedug", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/pricedug", "run", "serve" ]

[services.env]
PORT = "26152"
BASE_PATH = "/"
